// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvzAX5ysI8GmzZnHBoqke01fL_SPirdPw',
    appId: '1:296261998626:web:91808d306d89062ccfd27b',
    messagingSenderId: '296261998626',
    projectId: 'clothing-store-1caad',
    authDomain: 'clothing-store-1caad.firebaseapp.com',
    storageBucket: 'clothing-store-1caad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoPhhuN1U1GFjXtalBh4cf1xWUOxmOnK4',
    appId: '1:296261998626:android:855f00c527ee0c85cfd27b',
    messagingSenderId: '296261998626',
    projectId: 'clothing-store-1caad',
    storageBucket: 'clothing-store-1caad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-b18kR63pRcQAnIq8IUZcm8jpI3VgK0',
    appId: '1:296261998626:ios:045c82c6264fb3f6cfd27b',
    messagingSenderId: '296261998626',
    projectId: 'clothing-store-1caad',
    storageBucket: 'clothing-store-1caad.appspot.com',
    iosClientId: '296261998626-iriauvv7c713vdboqjhf6aev09c6dhoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothingStore',
  );
}
